# Generated by Django 5.0.7 on 2024-08-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('idencuesta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta1', models.BooleanField()),
                ('pregunta2', models.BooleanField()),
                ('pregunta3', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('idexamen', models.AutoField(primary_key=True, serialize=False)),
                ('fexamen', models.DateField()),
                ('fsintomas', models.DateField()),
                ('fiebre', models.BooleanField()),
                ('dcabeza', models.BooleanField()),
                ('dojos', models.BooleanField()),
                ('dmuscular', models.BooleanField()),
                ('nauseas', models.BooleanField()),
                ('fatiga', models.BooleanField()),
                ('sarpuido', models.BooleanField()),
                ('dabdominal', models.BooleanField()),
                ('vpersistentes', models.BooleanField()),
                ('respiracionRapida', models.BooleanField()),
                ('sangrado', models.BooleanField()),
                ('cansancio', models.BooleanField()),
                ('agitacion', models.BooleanField()),
                ('pielpalida', models.BooleanField()),
                ('orina', models.BooleanField()),
                ('otros', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apePaterno', models.CharField(max_length=50)),
                ('apeMaterno', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=15)),
                ('fnacimiento', models.DateField()),
                ('contra', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.CharField(blank=True, max_length=3, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.AutoField(primary_key=True, serialize=False)),
                ('idencuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediagnostico.encuesta')),
                ('idexamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediagnostico.examen')),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediagnostico.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='idpaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediagnostico.paciente'),
        ),
    ]
