# Generated by Django 5.0.7 on 2024-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='fexamen',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta1',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta3',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='agitacion',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='cansancio',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='dabdominal',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='dcabeza',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='dmuscular',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='dojos',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fatiga',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fiebre',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='nauseas',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='orina',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='otros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='pielpalida',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='respiracionRapida',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='resultado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='sangrado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='sarpuido',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='examen',
            name='vpersistentes',
            field=models.CharField(max_length=2),
        ),
    ]
