# Generated by Django 5.0.7 on 2024-08-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0002_remove_examen_fexamen_alter_encuesta_pregunta1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='idpaciente',
        ),
        migrations.AlterField(
            model_name='examen',
            name='otros',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
