# Generated by Django 5.0.7 on 2024-09-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0004_alter_encuesta_pregunta1_alter_encuesta_pregunta2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='agitacion',
            new_name='diarrea',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='cansancio',
            new_name='nvomitos',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='fatiga',
            new_name='papetito',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='nauseas',
            new_name='smetal',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='orina',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='pielpalida',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='respiracionRapida',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='sangrado',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='sarpuido',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='vpersistentes',
        ),
    ]
