# Generated by Django 5.0.7 on 2024-09-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0005_rename_agitacion_examen_diarrea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='dabdominal',
            new_name='addominal_pain',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='dcabeza',
            new_name='appetite_loss',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='diarrea',
            new_name='current_temp',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='dmuscular',
            new_name='diarrhoea',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='dojos',
            new_name='joint_muscle_aches',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='fiebre',
            new_name='metallic_taste_in_the_mouth',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='nvomitos',
            new_name='nausea_vomiting',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='papetito',
            new_name='pain_behind_the_eyes',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='smetal',
            new_name='servere_headche',
        ),
    ]
