# Generated by Django 5.0.7 on 2024-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0006_rename_dabdominal_examen_addominal_pain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='documento',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
