# Generated by Django 5.0.7 on 2024-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0007_alter_paciente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contra',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fnacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
