# Generated by Django 5.0.7 on 2024-09-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0008_alter_paciente_contra_alter_paciente_fnacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='idpaciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prediagnostico.paciente'),
        ),
    ]
