# Generated by Django 5.0.7 on 2024-09-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0009_examen_idpaciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='idpaciente',
            new_name='pkpaciente',
        ),
    ]
