# Generated by Django 5.0.7 on 2024-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0011_alter_historial_idencuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta3',
            field=models.CharField(),
        ),
    ]
