# Generated by Django 5.0.7 on 2024-09-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0013_encuesta_idpaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='idencuesta',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='idhistorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prediagnostico.historial'),
        ),
    ]
