# Generated by Django 5.0.7 on 2024-10-05 16:52

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0015_paciente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 17, 52, 10, 748288, tzinfo=datetime.timezone.utc)),
        ),
    ]
