# Generated by Django 5.0.7 on 2024-10-05 18:02

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0017_alter_paciente_correo_alter_paciente_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 19, 2, 30, 516901, tzinfo=datetime.timezone.utc)),
        ),
    ]
