# Generated by Django 5.0.7 on 2024-10-10 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0019_alter_paciente_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apeMaterno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apePaterno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 19, 20, 20, 552770, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
